import { BeLoveEvent } from "./types";

export const mockEvents: BeLoveEvent[] = [
  // ─── APRIL ───────────────────────────────────────────────────────────────
  {
    id: "1",
    name: "Houston Half Marathon",
    date: "2026-04-19T07:00:00",
    endDate: "2026-04-19T13:00:00",
    location: "Memorial Park",
    address: "6501 Memorial Dr, Houston, TX 77007",
    estimatedAttendance: 8000,
    eventType: "Fitness",
    isOutdoor: true,
    isRecurring: true,
    recurringPattern: "Annual",
    sourceUrl: "https://www.houstonhalf.com",
    source: "Eventbrite",
    description:
      "One of Houston's premier running events through scenic Memorial Park.",
    brandFitScore: 9,
    audienceFit: "Health-conscious adults 25–45, strong wellness orientation",
    samplingViability: "High",
    activationIdea:
      "Set up a recovery hydration station at the finish line. Pair Be Love with post-run messaging. Branded cups + QR code to Instagram.",
    permitConsiderations:
      "City of Houston Special Event Permit required — apply 60 days prior. Coordinate with race director for booth placement.",
    reasoning:
      "Post-race audience is maximally receptive to hydration products. Health-forward demographic aligns perfectly with Be Love brand values.",
    status: "pending",
    discoveredAt: "2026-04-07T08:00:00",
    calendarAdded: false,
  },
  {
    id: "2",
    name: "UH Spring Fest",
    date: "2026-04-18T11:00:00",
    endDate: "2026-04-18T20:00:00",
    location: "University of Houston Campus",
    address: "4800 Calhoun Rd, Houston, TX 77004",
    estimatedAttendance: 12000,
    eventType: "College",
    isOutdoor: true,
    isRecurring: true,
    recurringPattern: "Annual",
    sourceUrl: "https://uh.edu/events",
    source: "Meetup",
    description:
      "UH's annual spring celebration featuring live music, food, games, and campus-wide activities.",
    brandFitScore: 8,
    audienceFit: "College students 18–24, diverse, social and trend-conscious",
    samplingViability: "High",
    activationIdea:
      "High-energy sampling booth with branded merch giveaway. Run a social media challenge — tag @belove for a free can.",
    permitConsiderations:
      "Requires UH Student Affairs vendor approval. Apply through Office of Student Activities.",
    reasoning:
      "Core target demographic at scale. Outdoor campus quad, highly social atmosphere. Students share experiences heavily on social media.",
    status: "pending",
    discoveredAt: "2026-04-07T08:00:00",
    calendarAdded: false,
  },
  {
    id: "3",
    name: "EaDo Night Market",
    date: "2026-04-17T18:00:00",
    endDate: "2026-04-17T22:00:00",
    location: "East Downtown (EaDo)",
    address: "2500 Commerce St, Houston, TX 77003",
    estimatedAttendance: 2500,
    eventType: "Pop-up",
    isOutdoor: true,
    isRecurring: true,
    recurringPattern: "Monthly",
    sourceUrl: "https://www.eadonightmarket.com",
    source: "Do713",
    description:
      "Houston's coolest monthly night market in the vibrant EaDo neighborhood. Local vendors, street food, live DJ, art installations.",
    brandFitScore: 8,
    audienceFit: "Trendy young creatives 21–35, diverse, social media active, early adopters",
    samplingViability: "High",
    activationIdea:
      "Neon-lit Be Love pop-up station. Limited edition night market can design. Partner with a local DJ for a Be Love set.",
    permitConsiderations:
      "Contact EaDo Night Market organizers directly for vendor spots. Monthly recurring means you can test once and scale.",
    reasoning:
      "Monthly cadence allows for testing and optimization. Trendy crowd with high social media presence = earned media multiplier.",
    status: "pending",
    discoveredAt: "2026-04-07T08:00:00",
    calendarAdded: false,
  },

  // ─── MAY ─────────────────────────────────────────────────────────────────
  {
    id: "4",
    name: "Bayou City Art Festival",
    date: "2026-05-02T10:00:00",
    endDate: "2026-05-04T18:00:00",
    location: "Memorial Park",
    address: "6501 Memorial Dr, Houston, TX 77007",
    estimatedAttendance: 75000,
    eventType: "Festival",
    isOutdoor: true,
    isRecurring: true,
    recurringPattern: "Annual (Spring + Fall)",
    sourceUrl: "https://www.bayoucityartfestival.com",
    source: "Houston365",
    description:
      "One of the top 10 outdoor fine arts festivals in the US. Three days of art, food, live music, and family activities.",
    brandFitScore: 8,
    audienceFit: "Affluent arts patrons, young professionals, families 28–50",
    samplingViability: "High",
    activationIdea:
      "Branded sampling station near food vendor row. Create an 'art of refreshment' Instagram moment. Offer 3-day sampling with day-over-day loyalty reward.",
    permitConsiderations:
      "Vendor applications open Dec–Feb. Booth fee approx $500–$1,500. Apply through Bayou City Art Festival vendor portal.",
    reasoning:
      "Massive attendance over 3 days. Outdoor festival atmosphere, all-day foot traffic, mix of demographics.",
    status: "pending",
    discoveredAt: "2026-04-07T08:00:00",
    calendarAdded: false,
  },
  {
    id: "5",
    name: "Houston Triathlon",
    date: "2026-05-17T06:00:00",
    endDate: "2026-05-17T14:00:00",
    location: "Sylvan Beach Park",
    address: "400 Sylvan Beach Dr, La Porte, TX 77571",
    estimatedAttendance: 2200,
    eventType: "Fitness",
    isOutdoor: true,
    isRecurring: true,
    recurringPattern: "Annual",
    sourceUrl: "https://www.houstontriathlon.com",
    source: "Eventbrite",
    description:
      "Annual triathlon drawing serious athletes and fitness enthusiasts from across Texas.",
    brandFitScore: 9,
    audienceFit: "Elite fitness enthusiasts 28–45, high income, health-obsessed, premium product buyers",
    samplingViability: "High",
    activationIdea:
      "Recovery station at transition zones and finish line. 'Fuel the Finish' campaign with Be Love. Partner for official hydration partner status.",
    permitConsiderations:
      "Coordinate with race director for official vendor/sponsor status. La Porte city permit may be required.",
    reasoning:
      "Highly engaged fitness audience with maximum brand alignment. Triathlon community is influential, tight-knit, and vocal about products they love.",
    status: "pending",
    discoveredAt: "2026-04-07T08:00:00",
    calendarAdded: false,
  },
  {
    id: "6",
    name: "Discovery Green Picnic in the Park",
    date: "2026-05-09T17:00:00",
    endDate: "2026-05-09T21:00:00",
    location: "Discovery Green Park",
    address: "1500 McKinney St, Houston, TX 77010",
    estimatedAttendance: 4000,
    eventType: "Concert",
    isOutdoor: true,
    isRecurring: true,
    recurringPattern: "Monthly (spring/summer)",
    sourceUrl: "https://www.discoverygreen.com",
    source: "Discovery Green",
    description:
      "Free outdoor concert series in the heart of downtown Houston at Discovery Green. Families, young professionals, and locals gather on the lawn for live music and food trucks.",
    brandFitScore: 9,
    audienceFit:
      "Downtown professionals, young families, active lifestyle 22–40. Health-conscious urban crowd",
    samplingViability: "High",
    activationIdea:
      "Blanket-side sampling cart weaving through picnic areas. 'Sip & Chill' activation with branded blankets and cups. Perfect backdrop for lifestyle content creation.",
    permitConsiderations:
      "Contact Discovery Green events team for vendor/sponsor partnerships. As a park venue, requires Discovery Green management approval. Relatively low barrier.",
    reasoning:
      "Discovery Green attracts exactly the Be Love demographic — health-conscious, social, downtown Houston crowd. Relaxed outdoor setting with high dwell time is perfect for sampling.",
    status: "pending",
    discoveredAt: "2026-04-07T08:00:00",
    calendarAdded: false,
  },
  {
    id: "7",
    name: "GRB Health & Wellness Expo",
    date: "2026-05-15T09:00:00",
    endDate: "2026-05-16T17:00:00",
    location: "George R. Brown Convention Center",
    address: "1001 Avenida De Las Americas, Houston, TX 77010",
    estimatedAttendance: 18000,
    eventType: "Festival",
    isOutdoor: false,
    isRecurring: true,
    recurringPattern: "Annual",
    sourceUrl: "https://www.grbhouston.com",
    source: "GRB Convention Center",
    description:
      "Houston's largest health and wellness expo featuring fitness brands, nutrition products, wellness services, and keynote speakers on healthy living.",
    brandFitScore: 10,
    audienceFit:
      "Health enthusiasts, nutrition-focused consumers, fitness professionals 20–50. Highest possible brand alignment.",
    samplingViability: "High",
    activationIdea:
      "Prime vendor booth placement in the nutrition/beverage aisle. Product demo station with branded health messaging. Collect leads via QR code for loyalty program sign-up.",
    permitConsiderations:
      "Booth rental through GRB exhibitor program. Apply 3–4 months in advance. Standard exhibitor insurance required ($1M liability). Booth fee ~$1,500–$3,000.",
    reasoning:
      "Perfect brand-event alignment — attendees are specifically seeking health products. High intent audience with purchase mindset. Two full days of exposure.",
    status: "pending",
    discoveredAt: "2026-04-07T08:00:00",
    calendarAdded: false,
  },
  {
    id: "8",
    name: "Houston Yoga Festival",
    date: "2026-05-25T08:00:00",
    endDate: "2026-05-25T17:00:00",
    location: "Buffalo Bayou Park",
    address: "105 Sabine St, Houston, TX 77007",
    estimatedAttendance: 3500,
    eventType: "Fitness",
    isOutdoor: true,
    isRecurring: false,
    sourceUrl: "https://www.houstonyogafestival.com",
    source: "Eventbrite",
    description:
      "A full-day outdoor yoga and wellness festival on the banks of Buffalo Bayou. Multiple stages, sound baths, wellness vendors, and healthy food.",
    brandFitScore: 10,
    audienceFit:
      "Wellness-focused females 25–40, mindful consumers, premium brand affinities",
    samplingViability: "High",
    activationIdea:
      "Positioned as official hydration partner. Sampling between yoga sessions with 'restore with Be Love' messaging. Collaborate with instructors for product mentions.",
    permitConsiderations:
      "Buffalo Bayou Park events require Houston Parks Board approval. Coordinate with festival organizers for official sponsorship or vendor slot.",
    reasoning:
      "Highest possible brand alignment — wellness, outdoor, mindful lifestyle audience. A natural extension of Be Love's brand values.",
    status: "pending",
    discoveredAt: "2026-04-07T08:00:00",
    calendarAdded: false,
  },
  {
    id: "9",
    name: "Heights Farmers Market",
    date: "2026-05-02T08:00:00",
    endDate: "2026-05-02T12:00:00",
    location: "Heights Mercantile",
    address: "714 Yale St, Houston, TX 77007",
    estimatedAttendance: 2000,
    eventType: "Market",
    isOutdoor: true,
    isRecurring: true,
    recurringPattern: "Every Saturday",
    sourceUrl: "https://www.theheightshouston.com/market",
    source: "Meetup",
    description:
      "Houston's most beloved weekly farmers market in the heart of the Heights neighborhood. Local produce, artisan goods, food trucks, and a strong wellness community.",
    brandFitScore: 9,
    audienceFit:
      "Health-conscious locals 25–40, strong organic/wellness orientation, high disposable income",
    samplingViability: "High",
    activationIdea:
      "Weekly sampling table with loyalty punch card for repeat visitors. Partner with complementary vendors for cross-promotion bundles.",
    permitConsiderations:
      "Vendor fee ~$75/week. Contact Heights Mercantile directly. No city permit needed for recurring private market vendors.",
    reasoning:
      "Perfect weekly recurring touchpoint with exactly the right demographic. Wellness-aligned community, high receptivity, low cost to activate.",
    status: "approved",
    discoveredAt: "2026-04-07T08:00:00",
    calendarAdded: true,
  },

  // ─── JUNE ────────────────────────────────────────────────────────────────
  {
    id: "10",
    name: "Free Press Summer Fest",
    date: "2026-06-06T12:00:00",
    endDate: "2026-06-07T23:00:00",
    location: "Eleanor Tinsley Park",
    address: "3300 Allen Pkwy, Houston, TX 77019",
    estimatedAttendance: 35000,
    eventType: "Concert",
    isOutdoor: true,
    isRecurring: true,
    recurringPattern: "Annual",
    sourceUrl: "https://www.freepresssummerfest.com",
    source: "Ticketmaster",
    description:
      "Houston's beloved 2-day indie music festival along Buffalo Bayou with multiple stages, local food vendors, and a cool creative crowd.",
    brandFitScore: 7,
    audienceFit: "Indie music fans 21–35, creative professionals, culturally engaged",
    samplingViability: "Medium",
    activationIdea:
      "Sponsor the 'chill zone' near the smaller stage. Cold sampling on hot summer days. Be Love music playlist tie-in on Spotify promoted at the event.",
    permitConsiderations:
      "Official vendor/sponsor application through Free Press Houston. Ensure no exclusivity conflicts with official sponsors.",
    reasoning:
      "Strong demographic fit with 35K attendance. Summer heat makes cold beverage sampling very effective. Creative crowd aligns with Be Love aesthetic.",
    status: "pending",
    discoveredAt: "2026-04-07T08:00:00",
    calendarAdded: false,
  },
  {
    id: "11",
    name: "Discovery Green Summer Movie Series",
    date: "2026-06-12T20:00:00",
    endDate: "2026-06-12T23:00:00",
    location: "Discovery Green Park",
    address: "1500 McKinney St, Houston, TX 77010",
    estimatedAttendance: 3000,
    eventType: "Community",
    isOutdoor: true,
    isRecurring: true,
    recurringPattern: "Weekly (June–Aug)",
    sourceUrl: "https://www.discoverygreen.com/movies",
    source: "Discovery Green",
    description:
      "Free outdoor movie screenings every Friday night at Discovery Green all summer long. Houstonians bring blankets and picnic setups to watch films under the stars.",
    brandFitScore: 8,
    audienceFit:
      "Young professionals and families 22–40, social and relaxed, downtown Houston residents",
    samplingViability: "High",
    activationIdea:
      "Pre-movie sampling station at park entrance. 'Movie Night Kit' — Be Love + branded popcorn bag combo. Great branded photo op with movie screen backdrop.",
    permitConsiderations:
      "Partner directly with Discovery Green management for vendor spots. Weekly recurring event makes this a cost-effective summer-long activation.",
    reasoning:
      "Recurring weekly event = consistent touchpoint all summer. Relaxed, social atmosphere with high dwell time. Ideal for building brand familiarity over the season.",
    status: "pending",
    discoveredAt: "2026-04-07T08:00:00",
    calendarAdded: false,
  },
  {
    id: "12",
    name: "GRB Houston Food & Wine Festival",
    date: "2026-06-20T14:00:00",
    endDate: "2026-06-21T21:00:00",
    location: "George R. Brown Convention Center",
    address: "1001 Avenida De Las Americas, Houston, TX 77010",
    estimatedAttendance: 22000,
    eventType: "Festival",
    isOutdoor: false,
    isRecurring: true,
    recurringPattern: "Annual",
    sourceUrl: "https://www.grbhouston.com",
    source: "GRB Convention Center",
    description:
      "Two days of curated food, wine, and beverage experiences featuring Houston's top chefs, sommeliers, and artisan brands inside the GRB.",
    brandFitScore: 9,
    audienceFit:
      "Affluent foodies and beverage enthusiasts 28–55, high disposable income, premium brand buyers",
    samplingViability: "High",
    activationIdea:
      "Featured beverage booth in the artisan drinks section. Pair Be Love with local food pairings. Offer a 'clean refreshment' angle alongside wine and spirits.",
    permitConsiderations:
      "Exhibitor application through GRB events team. Beverage sampling may require Texas TABC license. Standard liability insurance required.",
    reasoning:
      "Premium audience actively seeking new beverage experiences. Be Love fits perfectly in the artisan/craft beverage category. High purchase intent and media coverage.",
    status: "pending",
    discoveredAt: "2026-04-07T08:00:00",
    calendarAdded: false,
  },
  {
    id: "13",
    name: "Houston Pride Festival",
    date: "2026-06-27T12:00:00",
    endDate: "2026-06-27T22:00:00",
    location: "Downtown Houston",
    address: "500 Bagby St, Houston, TX 77002",
    estimatedAttendance: 700000,
    eventType: "Festival",
    isOutdoor: true,
    isRecurring: true,
    recurringPattern: "Annual",
    sourceUrl: "https://www.pridehouston.org",
    source: "Houston Press",
    description:
      "One of the largest Pride celebrations in the US, drawing hundreds of thousands to downtown Houston for a parade, festival, and live performances.",
    brandFitScore: 8,
    audienceFit:
      "Extremely broad — LGBTQ+ community, allies, young adults 18–45, love and inclusion-focused",
    samplingViability: "High",
    activationIdea:
      "Be Love Pride activation — 'Love is the Ingredient' campaign. Branded rainbow cups, high-energy street sampling. Potential parade float or booth partnership with community org.",
    permitConsiderations:
      "Vendor applications through Pride Houston. Very competitive — apply 4–6 months early. City street vendor permit required. Massive logistics — bring large team.",
    reasoning:
      "Be Love's name is perfectly aligned with Pride's message of love. Massive scale (700K). Brand values of love and community fit naturally. Exceptional earned media opportunity.",
    status: "pending",
    discoveredAt: "2026-04-07T08:00:00",
    calendarAdded: false,
  },
  {
    id: "14",
    name: "Discovery Green Yoga in the Park",
    date: "2026-06-07T08:00:00",
    endDate: "2026-06-07T10:00:00",
    location: "Discovery Green Park",
    address: "1500 McKinney St, Houston, TX 77010",
    estimatedAttendance: 600,
    eventType: "Fitness",
    isOutdoor: true,
    isRecurring: true,
    recurringPattern: "Weekly (Sundays)",
    sourceUrl: "https://www.discoverygreen.com/yoga",
    source: "Discovery Green",
    description:
      "Free weekly Sunday morning yoga classes on the Discovery Green lawn. Led by local instructors, open to all skill levels.",
    brandFitScore: 10,
    audienceFit:
      "Health-focused urban professionals 25–40, wellness lifestyle, predominantly female, high brand affinity",
    samplingViability: "High",
    activationIdea:
      "Post-class recovery sampling — 'Restore with Be Love.' Set up right at the mat pickup area. Small, intimate setting = high personal connection with the brand.",
    permitConsiderations:
      "Partner with Discovery Green directly. Low-cost activation. Recurring weekly means high cumulative reach throughout summer.",
    reasoning:
      "Perfect micro-activation opportunity. Weekly cadence builds a loyal Be Love association with the yoga community. Intimate setting creates genuine brand relationships.",
    status: "pending",
    discoveredAt: "2026-04-07T08:00:00",
    calendarAdded: false,
  },
  {
    id: "15",
    name: "Houston Dragon Boat Festival",
    date: "2026-06-13T08:00:00",
    endDate: "2026-06-13T17:00:00",
    location: "Buffalo Bayou Park",
    address: "105 Sabine St, Houston, TX 77007",
    estimatedAttendance: 15000,
    eventType: "Sports",
    isOutdoor: true,
    isRecurring: true,
    recurringPattern: "Annual",
    sourceUrl: "https://www.houstondragonboat.org",
    source: "Houston Chronicle Events",
    description:
      "Annual dragon boat racing festival on Buffalo Bayou celebrating Asian culture, athletic competition, and community spirit.",
    brandFitScore: 7,
    audienceFit: "Active adults 25–45, diverse, community-oriented, athletic",
    samplingViability: "High",
    activationIdea:
      "Sampling tent near spectator viewing areas. 'Power Your Paddle' messaging. Great multicultural brand exposure.",
    permitConsiderations:
      "Vendor application through Houston Dragon Boat Festival org. Buffalo Bayou Park permit required.",
    reasoning:
      "Active outdoor event with healthy, community-driven crowd. Good attendance with a mix of participants and spectators. Strong community feel aligns with Be Love values.",
    status: "pending",
    discoveredAt: "2026-04-07T08:00:00",
    calendarAdded: false,
  },

  // ─── JULY ────────────────────────────────────────────────────────────────
  {
    id: "16",
    name: "GRB Comic Con Houston",
    date: "2026-07-10T10:00:00",
    endDate: "2026-07-12T19:00:00",
    location: "George R. Brown Convention Center",
    address: "1001 Avenida De Las Americas, Houston, TX 77010",
    estimatedAttendance: 95000,
    eventType: "Festival",
    isOutdoor: false,
    isRecurring: true,
    recurringPattern: "Annual",
    sourceUrl: "https://www.comicconhouston.com",
    source: "GRB Convention Center",
    description:
      "Houston's massive 3-day pop culture convention featuring comics, gaming, celebrity panels, cosplay, and fan experiences.",
    brandFitScore: 6,
    audienceFit: "Geek culture fans 16–40, broad demographics, high energy and social",
    samplingViability: "Medium",
    activationIdea:
      "Fun branded pop culture angle — 'The Drink of Heroes.' Booth near food court area. Partner with artist alley for limited edition Be Love fan art can design.",
    permitConsiderations:
      "Exhibitor application through GRB. Very high traffic — bring large team and high volume of samples. 3-day commitment. Booth fee $2,000–$5,000+.",
    reasoning:
      "Massive scale (95K over 3 days) gives exceptional volume. Younger demographic skew is valuable. Indoor climate-controlled = sampling-friendly. Be Love brand can be playful here.",
    status: "pending",
    discoveredAt: "2026-04-07T08:00:00",
    calendarAdded: false,
  },
  {
    id: "17",
    name: "Discovery Green 4th of July Celebration",
    date: "2026-07-04T17:00:00",
    endDate: "2026-07-04T23:00:00",
    location: "Discovery Green Park",
    address: "1500 McKinney St, Houston, TX 77010",
    estimatedAttendance: 25000,
    eventType: "Festival",
    isOutdoor: true,
    isRecurring: true,
    recurringPattern: "Annual",
    sourceUrl: "https://www.discoverygreen.com/july4",
    source: "Discovery Green",
    description:
      "Houston's beloved downtown 4th of July celebration at Discovery Green with live music, food, family activities, and fireworks over the city skyline.",
    brandFitScore: 9,
    audienceFit:
      "Broad Houston community, families and young adults 21–45, patriotic and celebratory mood",
    samplingViability: "High",
    activationIdea:
      "Patriotic Be Love activation — red, white, and love branding. Ice-cold sampling in peak July heat. Fireworks-viewing branded experience. Family-friendly sampling area.",
    permitConsiderations:
      "Partner with Discovery Green management. High-demand event — secure vendor spot 6+ months in advance. July heat requires substantial ice/cooling logistics.",
    reasoning:
      "25,000 attendees at a free outdoor event in July heat = perfect conditions for cold beverage sampling. Downtown Houston location reaches diverse, broad demographic.",
    status: "pending",
    discoveredAt: "2026-04-07T08:00:00",
    calendarAdded: false,
  },
  {
    id: "18",
    name: "Houston Summer Splash 5K",
    date: "2026-07-18T07:00:00",
    endDate: "2026-07-18T12:00:00",
    location: "Hermann Park",
    address: "6001 Fannin St, Houston, TX 77030",
    estimatedAttendance: 3500,
    eventType: "Fitness",
    isOutdoor: true,
    isRecurring: true,
    recurringPattern: "Annual",
    sourceUrl: "https://www.houstonrunningclub.com",
    source: "Eventbrite",
    description:
      "Summer fun run through Hermann Park with water stations, post-race festival, food trucks, and live music. A community favorite for casual runners.",
    brandFitScore: 9,
    audienceFit:
      "Casual fitness enthusiasts 22–40, community-oriented, health-conscious, family-friendly",
    samplingViability: "High",
    activationIdea:
      "Official post-race hydration partner. 'Beat the Heat with Be Love' campaign. Set up at finish line festival area with ice-cold cans and branded cooling towels.",
    permitConsiderations:
      "Hermann Park Conservancy event permit required. Coordinate with race organizers. July heat — logistics need extra cooling infrastructure.",
    reasoning:
      "Post-run in July heat = maximum receptivity to cold beverages. Community fun run draws approachable, friendly crowd. Casual fitness angle perfectly fits Be Love's accessible wellness brand.",
    status: "pending",
    discoveredAt: "2026-04-07T08:00:00",
    calendarAdded: false,
  },
  {
    id: "19",
    name: "GRB Houston International Boat Show",
    date: "2026-07-24T10:00:00",
    endDate: "2026-07-27T20:00:00",
    location: "George R. Brown Convention Center",
    address: "1001 Avenida De Las Americas, Houston, TX 77010",
    estimatedAttendance: 40000,
    eventType: "Festival",
    isOutdoor: false,
    isRecurring: true,
    recurringPattern: "Annual",
    sourceUrl: "https://www.grbhouston.com/boat-show",
    source: "GRB Convention Center",
    description:
      "One of the largest boat shows in the South. Four days of marine life, luxury boats, outdoor gear, and active lifestyle brands.",
    brandFitScore: 7,
    audienceFit:
      "Active outdoor/water sports enthusiasts, higher income adults 30–55, Texas lifestyle",
    samplingViability: "Medium",
    activationIdea:
      "Sampling near the outdoor/marine lifestyle section. 'Lake Life, Be Love' campaign angle. Pair with sunscreen/sunglasses brands for a summer lifestyle bundle giveaway.",
    permitConsiderations:
      "Exhibitor application through GRB or boat show organizers. Standard vendor insurance required. 4-day commitment with high foot traffic.",
    reasoning:
      "Active lifestyle audience with outdoor, adventurous mindset. Be Love fits the active recreation demographic. Good volume at 40K over 4 days.",
    status: "pending",
    discoveredAt: "2026-04-07T08:00:00",
    calendarAdded: false,
  },
  {
    id: "20",
    name: "Discovery Green Food Truck Friday",
    date: "2026-07-10T17:00:00",
    endDate: "2026-07-10T21:00:00",
    location: "Discovery Green Park",
    address: "1500 McKinney St, Houston, TX 77010",
    estimatedAttendance: 2000,
    eventType: "Pop-up",
    isOutdoor: true,
    isRecurring: true,
    recurringPattern: "Every Friday (summer)",
    sourceUrl: "https://www.discoverygreen.com/foodtrucks",
    source: "Discovery Green",
    description:
      "Weekly summer Friday food truck gathering at Discovery Green with rotating local trucks, live DJ, and an after-work social vibe.",
    brandFitScore: 9,
    audienceFit:
      "Young downtown professionals 22–38, after-work social crowd, trend-conscious, urban",
    samplingViability: "High",
    activationIdea:
      "Weekly sampling partner — 'Friday Refresh' with Be Love. Set up adjacent to food truck queue for maximum impulse trial. Pair with a food truck for a Be Love combo meal deal.",
    permitConsiderations:
      "Recurring partnership with Discovery Green management. Weekly commitment throughout summer. Very low barrier — Discovery Green actively seeks beverage partners.",
    reasoning:
      "Weekly after-work crowd is exactly the young professional demographic Be Love targets. Food truck pairing creates natural consumption moment. Low cost for high recurring reach.",
    status: "pending",
    discoveredAt: "2026-04-07T08:00:00",
    calendarAdded: false,
  },

  // ─── AUGUST ──────────────────────────────────────────────────────────────
  {
    id: "21",
    name: "Houston Back to School Bash",
    date: "2026-08-08T12:00:00",
    endDate: "2026-08-08T20:00:00",
    location: "NRG Park Parking Lot C",
    address: "8400 Kirby Dr, Houston, TX 77054",
    estimatedAttendance: 20000,
    eventType: "Community",
    isOutdoor: true,
    isRecurring: true,
    recurringPattern: "Annual",
    sourceUrl: "https://www.houstontx.gov/events",
    source: "Visit Houston",
    description:
      "Massive free back-to-school event for Houston families providing school supplies, food, activities, and entertainment for kids and parents.",
    brandFitScore: 6,
    audienceFit: "Families, parents 25–45, community-focused, broad demographic",
    samplingViability: "Medium",
    activationIdea:
      "Family-friendly sampling table. 'Start the Year with Love' campaign. Partner with school supply giveaway booth for a branded Be Love + school kit bundle.",
    permitConsiderations:
      "City of Houston managed event — contact Parks & Recreation for vendor spots. Outdoor summer event needs cooling logistics.",
    reasoning:
      "Large community event with engaged parents. Be Love can reinforce its community values. Good awareness play even if conversion is lower than fitness events.",
    status: "pending",
    discoveredAt: "2026-04-07T08:00:00",
    calendarAdded: false,
  },
  {
    id: "22",
    name: "GRB Houston Auto Show",
    date: "2026-08-14T10:00:00",
    endDate: "2026-08-16T20:00:00",
    location: "George R. Brown Convention Center",
    address: "1001 Avenida De Las Americas, Houston, TX 77010",
    estimatedAttendance: 55000,
    eventType: "Festival",
    isOutdoor: false,
    isRecurring: true,
    recurringPattern: "Annual",
    sourceUrl: "https://www.grbhouston.com/auto-show",
    source: "GRB Convention Center",
    description:
      "One of the largest auto shows in Texas featuring new model unveilings, electric vehicles, test drives, and automotive lifestyle brands.",
    brandFitScore: 5,
    audienceFit: "Auto enthusiasts, broad 25–60 demographics, lifestyle aspirational buyers",
    samplingViability: "Medium",
    activationIdea:
      "Sampling near EV/lifestyle vehicle section. 'Drive Clean, Drink Clean' angle tying Be Love to the clean energy movement.",
    permitConsiderations:
      "Exhibitor application through GRB. 3-day commitment. Standard insurance required. Booth fee $1,500–$3,000.",
    reasoning:
      "Decent volume at 55K but demographic fit is weaker than pure wellness events. Works best as broad awareness play. EV section creates a natural 'clean lifestyle' hook.",
    status: "pending",
    discoveredAt: "2026-04-07T08:00:00",
    calendarAdded: false,
  },
  {
    id: "23",
    name: "Houston Wellness Weekend",
    date: "2026-08-22T09:00:00",
    endDate: "2026-08-23T18:00:00",
    location: "Discovery Green Park",
    address: "1500 McKinney St, Houston, TX 77010",
    estimatedAttendance: 8000,
    eventType: "Festival",
    isOutdoor: true,
    isRecurring: true,
    recurringPattern: "Annual",
    sourceUrl: "https://www.discoverygreen.com/wellness",
    source: "Discovery Green",
    description:
      "Two-day wellness festival at Discovery Green featuring fitness classes, meditation, holistic health vendors, plant-based food, and wellness speakers.",
    brandFitScore: 10,
    audienceFit:
      "Wellness-devoted adults 22–45, health-first mindset, premium product buyers, influencer-adjacent",
    samplingViability: "High",
    activationIdea:
      "Headline beverage sponsor. 'Be Love, Be Well' campaign. Sampling at every session transition. Collaborate with wellness speakers for product mentions. Live social media content creation.",
    permitConsiderations:
      "Early sponsorship/vendor application to Discovery Green management. Premium placement opportunity as official beverage partner. Negotiate signage rights.",
    reasoning:
      "Best possible event for Be Love — 100% wellness audience, outdoor, 2-day format, influencer attendance likely. This event could define Be Love's Houston presence.",
    status: "pending",
    discoveredAt: "2026-04-07T08:00:00",
    calendarAdded: false,
  },

  // ─── SEPTEMBER ───────────────────────────────────────────────────────────
  {
    id: "24",
    name: "Bayou City Art Festival (Fall)",
    date: "2026-09-26T10:00:00",
    endDate: "2026-09-27T18:00:00",
    location: "Downtown Houston",
    address: "1000 Avenida De Las Americas, Houston, TX 77010",
    estimatedAttendance: 60000,
    eventType: "Festival",
    isOutdoor: true,
    isRecurring: true,
    recurringPattern: "Annual (Fall edition)",
    sourceUrl: "https://www.bayoucityartfestival.com",
    source: "Houston365",
    description:
      "The fall edition of Houston's beloved fine arts festival, set in the heart of downtown. Two days of sculpture, painting, jewelry, food, and live music.",
    brandFitScore: 8,
    audienceFit: "Affluent arts patrons, professionals 28–55, culturally engaged",
    samplingViability: "High",
    activationIdea:
      "Art-inspired Be Love activation — custom label design in partnership with a local artist at the festival. Sampling near the culinary arts section.",
    permitConsiderations:
      "Vendor applications open July–August for fall edition. Booth fee approx $500–$1,500.",
    reasoning:
      "60K attendance over 2 days in cooler fall weather. Great for outdoor sampling as temps drop. Strong repeat audience from spring edition.",
    status: "pending",
    discoveredAt: "2026-04-07T08:00:00",
    calendarAdded: false,
  },
  {
    id: "25",
    name: "Houston Greek Festival",
    date: "2026-09-11T12:00:00",
    endDate: "2026-09-13T22:00:00",
    location: "Annunciation Greek Orthodox Cathedral",
    address: "3511 Yoakum Blvd, Houston, TX 77006",
    estimatedAttendance: 50000,
    eventType: "Festival",
    isOutdoor: true,
    isRecurring: true,
    recurringPattern: "Annual",
    sourceUrl: "https://www.houstongreeekfestival.com",
    source: "Houston Press",
    description:
      "One of Houston's most beloved cultural festivals celebrating Greek food, music, dance, and community. A true Houston tradition for over 50 years.",
    brandFitScore: 7,
    audienceFit: "Broad Houston families and foodies 25–60, culturally curious, social",
    samplingViability: "High",
    activationIdea:
      "Mediterranean wellness angle — 'The Love of the Mediterranean.' Sampling alongside Greek food vendors. 'Be Love, Be Alive' campaign with Mediterranean imagery.",
    permitConsiderations:
      "Vendor application through Greek Festival organizers. Apply 3–4 months in advance. Outdoor festival with food vendor sections.",
    reasoning:
      "50K attendance over 3 days in pleasant September weather. Massive community event with strong foot traffic and social sharing.",
    status: "pending",
    discoveredAt: "2026-04-07T08:00:00",
    calendarAdded: false,
  },
  {
    id: "26",
    name: "GRB Natural Products Expo South",
    date: "2026-09-18T09:00:00",
    endDate: "2026-09-20T17:00:00",
    location: "George R. Brown Convention Center",
    address: "1001 Avenida De Las Americas, Houston, TX 77010",
    estimatedAttendance: 30000,
    eventType: "Festival",
    isOutdoor: false,
    isRecurring: true,
    recurringPattern: "Annual",
    sourceUrl: "https://www.grbhouston.com",
    source: "GRB Convention Center",
    description:
      "The Southeast's premier natural, organic, and healthy products trade show. Buyers, retailers, and health-conscious consumers explore the latest in wellness brands.",
    brandFitScore: 10,
    audienceFit:
      "Natural product buyers, health retailers, wellness entrepreneurs, and consumers 25–50. Highest possible industry alignment.",
    samplingViability: "High",
    activationIdea:
      "Exhibitor booth in the beverage section. Trade-facing pitch to retailers for distribution deals + consumer sampling. Use this as a B2B and B2C dual opportunity.",
    permitConsiderations:
      "Exhibitor application through Expo organizers. 3-day commitment. Standard liability insurance. Booth fee $2,000–$4,000 for standard space.",
    reasoning:
      "This is the single most strategically valuable event for Be Love — buyers who attend are looking to stock shelves with exactly this type of product. Distribution deals can be made here.",
    status: "pending",
    discoveredAt: "2026-04-07T08:00:00",
    calendarAdded: false,
  },
  {
    id: "27",
    name: "Houston Oktoberfest at Biergarten",
    date: "2026-09-25T16:00:00",
    endDate: "2026-09-27T23:00:00",
    location: "Saint Arnold Brewing Company",
    address: "2000 Lyons Ave, Houston, TX 77020",
    estimatedAttendance: 8000,
    eventType: "Festival",
    isOutdoor: true,
    isRecurring: true,
    recurringPattern: "Annual",
    sourceUrl: "https://www.saintarnold.com/events",
    source: "Do713",
    description:
      "Houston's beloved Oktoberfest celebration at Saint Arnold's outdoor biergarten with live bands, food, games, and a festive crowd.",
    brandFitScore: 6,
    audienceFit: "Young adults 21–40, social drinkers, fun-seeking, broad demographics",
    samplingViability: "Medium",
    activationIdea:
      "Position Be Love as the non-alcoholic/refreshing alternative. 'The Clean Option' activation alongside beer vendors. Great for designated driver audience.",
    permitConsiderations:
      "Coordinate with Saint Arnold Brewing for vendor spot. Non-alcoholic beverage may be welcomed as complementary offering.",
    reasoning:
      "High social energy crowd. Offering a clean, non-alcoholic alternative at a beer festival fills a real gap. Captures health-conscious attendees who don't drink.",
    status: "pending",
    discoveredAt: "2026-04-07T08:00:00",
    calendarAdded: false,
  },
  {
    id: "28",
    name: "Discovery Green Yoga & Wellness Weekend",
    date: "2026-09-12T08:00:00",
    endDate: "2026-09-13T17:00:00",
    location: "Discovery Green Park",
    address: "1500 McKinney St, Houston, TX 77010",
    estimatedAttendance: 5000,
    eventType: "Fitness",
    isOutdoor: true,
    isRecurring: true,
    recurringPattern: "Annual",
    sourceUrl: "https://www.discoverygreen.com/wellness",
    source: "Discovery Green",
    description:
      "Two-day fall wellness retreat at Discovery Green with yoga, meditation, sound healing, plant-based food vendors, and wellness speakers.",
    brandFitScore: 10,
    audienceFit: "Wellness devotees 22–45, health-first mindset, premium brand buyers",
    samplingViability: "High",
    activationIdea:
      "'Fall Reset with Be Love' campaign. Official hydration partner of the event. Sampling at every class transition. Collab with instructors for branded content.",
    permitConsiderations:
      "Direct partnership with Discovery Green management. Premium placement as official beverage sponsor. Negotiate signage rights.",
    reasoning:
      "100% wellness audience in ideal September weather. Cooler temps = more active participation and longer dwell time. Perfect brand alignment.",
    status: "pending",
    discoveredAt: "2026-04-07T08:00:00",
    calendarAdded: false,
  },
  {
    id: "29",
    name: "Houston Open (PGA Tour)",
    date: "2026-09-28T08:00:00",
    endDate: "2026-10-04T18:00:00",
    location: "Memorial Park Golf Course",
    address: "1001 E Memorial Loop, Houston, TX 77007",
    estimatedAttendance: 120000,
    eventType: "Sports",
    isOutdoor: true,
    isRecurring: true,
    recurringPattern: "Annual",
    sourceUrl: "https://www.houstongolfassoc.org",
    source: "Ticketmaster",
    description:
      "Houston's official PGA Tour event drawing world-class golfers and tens of thousands of spectators to Memorial Park over 7 days.",
    brandFitScore: 8,
    audienceFit:
      "Affluent sports fans and golf enthusiasts 30–60, high household income, premium lifestyle buyers",
    samplingViability: "Medium",
    activationIdea:
      "Sponsor the fan village or clubhouse refresh station. 'Course-side Hydration' campaign. Premium gifting suite inclusion for VIP guests.",
    permitConsiderations:
      "Official PGA Tour event — requires Houston Golf Association vendor/sponsor approval. Early application critical (6+ months). Significant investment but premium brand placement.",
    reasoning:
      "120K high-income attendees over 7 days. Golf audience skews affluent and health-conscious. Premium brand environment that elevates Be Love's positioning.",
    status: "pending",
    discoveredAt: "2026-04-07T08:00:00",
    calendarAdded: false,
  },
  {
    id: "30",
    name: "Montrose Art Walk",
    date: "2026-09-18T18:00:00",
    endDate: "2026-09-18T22:00:00",
    location: "Montrose Neighborhood",
    address: "Westheimer Rd & Montrose Blvd, Houston, TX 77006",
    estimatedAttendance: 3500,
    eventType: "Community",
    isOutdoor: true,
    isRecurring: true,
    recurringPattern: "Monthly",
    sourceUrl: "https://www.montrosecenter.org/artwalk",
    source: "CultureMap Houston",
    description:
      "Monthly evening art walk through Montrose galleries, studios, and pop-ups. Houston's creative heartbeat — local artists, installations, and a vibrant social scene.",
    brandFitScore: 8,
    audienceFit: "Creative professionals and artists 24–40, LGBTQ+-friendly, culturally aware, trend-forward",
    samplingViability: "High",
    activationIdea:
      "Pop-up sampling station at a featured gallery. 'Art of Refreshment' collab with a local painter for a limited Be Love can label. Monthly recurring presence builds strong brand identity in Montrose.",
    permitConsiderations:
      "Coordinate with Montrose Art Walk organizers or individual gallery hosts. Low cost, high cultural cachet.",
    reasoning:
      "Monthly recurring event in Houston's most culturally vibrant neighborhood. Creative audience = heavy social media sharing. Strong brand equity opportunity.",
    status: "pending",
    discoveredAt: "2026-04-07T08:00:00",
    calendarAdded: false,
  },

  // ─── OCTOBER ─────────────────────────────────────────────────────────────
  {
    id: "31",
    name: "Houston Marathon Training Kickoff",
    date: "2026-10-04T07:00:00",
    endDate: "2026-10-04T11:00:00",
    location: "Memorial Park",
    address: "6501 Memorial Dr, Houston, TX 77007",
    estimatedAttendance: 5000,
    eventType: "Fitness",
    isOutdoor: true,
    isRecurring: true,
    recurringPattern: "Annual",
    sourceUrl: "https://www.houstonmarathon.com",
    source: "Eventbrite",
    description:
      "Official kickoff of Houston Marathon training season. Thousands of runners gather for group runs, training tips, nutrition talks, and expo-style vendor booths.",
    brandFitScore: 10,
    audienceFit: "Dedicated runners and fitness enthusiasts 25–50, nutrition-focused, high brand loyalty",
    samplingViability: "High",
    activationIdea:
      "'Train with Be Love' seasonal campaign. Sampling at the nutrition expo section. Sponsor the hydration station on the training route. Offer a 'Be Love Training Pack' discount code.",
    permitConsiderations:
      "Coordinate with Houston Marathon organization for official vendor/sponsor status. Apply through houstonmarathon.com sponsors portal.",
    reasoning:
      "Beginning of marathon training season = high motivation and receptivity to new nutrition products. Very loyal, word-of-mouth-driven running community.",
    status: "pending",
    discoveredAt: "2026-04-07T08:00:00",
    calendarAdded: false,
  },
  {
    id: "32",
    name: "Houston Restaurant Weeks Fall Edition",
    date: "2026-10-01T11:00:00",
    endDate: "2026-10-31T22:00:00",
    location: "Citywide — Houston restaurants",
    address: "Various locations, Houston, TX",
    estimatedAttendance: 500000,
    eventType: "Community",
    isOutdoor: false,
    isRecurring: true,
    recurringPattern: "Annual (Aug + Oct)",
    sourceUrl: "https://www.houstonrestaurantweeks.com",
    source: "Houston Press",
    description:
      "Month-long dining promotion where Houston's top restaurants offer prix-fixe menus. Proceeds benefit the Houston Food Bank. A citywide culinary celebration.",
    brandFitScore: 7,
    audienceFit: "Foodies and diners 25–55, health-conscious fine diners, broad Houston demographics",
    samplingViability: "Medium",
    activationIdea:
      "Partner with 5–10 participating restaurants to feature Be Love on their prix-fixe beverage menu. 'Pair with Be Love' table cards. Co-branded social media posts with restaurant partners.",
    permitConsiderations:
      "Coordinate with Houston Restaurant Weeks organizers and individual restaurants. No permits needed — B2B partnership model.",
    reasoning:
      "Massive citywide reach without a single event cost. Restaurant partnership creates credibility and regular consumption habit. Be Love on menus = discovery for new customers.",
    status: "pending",
    discoveredAt: "2026-04-07T08:00:00",
    calendarAdded: false,
  },
  {
    id: "33",
    name: "GRB Houston Hobby Expo",
    date: "2026-10-09T09:00:00",
    endDate: "2026-10-11T18:00:00",
    location: "George R. Brown Convention Center",
    address: "1001 Avenida De Las Americas, Houston, TX 77010",
    estimatedAttendance: 35000,
    eventType: "Festival",
    isOutdoor: false,
    isRecurring: true,
    recurringPattern: "Annual",
    sourceUrl: "https://www.grbhouston.com",
    source: "GRB Convention Center",
    description:
      "Houston's largest hobby and maker expo — arts & crafts, DIY, home improvement, gaming, collectibles, and creative hobbies.",
    brandFitScore: 5,
    audienceFit: "Hobby enthusiasts and families, broad 20–60, creative DIY crowd",
    samplingViability: "Medium",
    activationIdea:
      "Sampling near the creative/lifestyle section. 'Fuel Your Creativity' angle. Partner with a DIY craft brand for a 'Be Love Creative Kit' giveaway.",
    permitConsiderations: "Standard GRB exhibitor application. 3-day commitment. Booth fee ~$1,500–$2,500.",
    reasoning:
      "Decent volume at 35K. Weaker brand fit than wellness events but good for broad awareness. Complement with a fun, creative brand angle.",
    status: "pending",
    discoveredAt: "2026-04-07T08:00:00",
    calendarAdded: false,
  },
  {
    id: "34",
    name: "Houston FearFest at NRG Park",
    date: "2026-10-16T18:00:00",
    endDate: "2026-10-16T23:00:00",
    location: "NRG Park",
    address: "1 NRG Pkwy, Houston, TX 77054",
    estimatedAttendance: 25000,
    eventType: "Festival",
    isOutdoor: true,
    isRecurring: true,
    recurringPattern: "Annual",
    sourceUrl: "https://www.nrgpark.com/events",
    source: "NRG Park Events",
    description:
      "Houston's massive Halloween festival at NRG Park with haunted attractions, live entertainment, costume contests, food vendors, and family zones.",
    brandFitScore: 6,
    audienceFit: "Young adults and families 16–35, fun-seeking, social, event-goers",
    samplingViability: "Medium",
    activationIdea:
      "'Scary Good' Halloween Be Love activation. Branded orange/black cups. Sampling in the food vendor area. Fun seasonal limited-edition can design reveal.",
    permitConsiderations: "Vendor application through NRG Park events team. Evening outdoor event — cooler October temps are favorable.",
    reasoning:
      "25K attendees in a festive evening setting. Younger demographic with strong social sharing. Fun brand angle for Halloween season.",
    status: "pending",
    discoveredAt: "2026-04-07T08:00:00",
    calendarAdded: false,
  },
  {
    id: "35",
    name: "Discovery Green Harvest Festival",
    date: "2026-10-17T11:00:00",
    endDate: "2026-10-18T20:00:00",
    location: "Discovery Green Park",
    address: "1500 McKinney St, Houston, TX 77010",
    estimatedAttendance: 12000,
    eventType: "Festival",
    isOutdoor: true,
    isRecurring: true,
    recurringPattern: "Annual",
    sourceUrl: "https://www.discoverygreen.com/harvest",
    source: "Discovery Green",
    description:
      "Two-day fall harvest festival at Discovery Green with farm-to-table food vendors, local makers, live music, and family activities celebrating the autumn season.",
    brandFitScore: 9,
    audienceFit: "Health-conscious families and young adults 22–45, farm-to-table mindset, local brand supporters",
    samplingViability: "High",
    activationIdea:
      "'Fall in Love with Be Love' harvest campaign. Sampling alongside farm-to-table vendors. Pair with seasonal apple/pumpkin spice flavor tie-in messaging.",
    permitConsiderations: "Direct partnership with Discovery Green management. Early application for vendor spots recommended.",
    reasoning:
      "Farm-to-table, local food crowd is perfectly aligned with Be Love's natural ingredient story. Great seasonal brand narrative with 12K engaged attendees.",
    status: "pending",
    discoveredAt: "2026-04-07T08:00:00",
    calendarAdded: false,
  },
  {
    id: "36",
    name: "Rice University Fall Fest",
    date: "2026-10-10T12:00:00",
    endDate: "2026-10-10T20:00:00",
    location: "Rice University Campus",
    address: "6100 Main St, Houston, TX 77005",
    estimatedAttendance: 6000,
    eventType: "College",
    isOutdoor: true,
    isRecurring: true,
    recurringPattern: "Annual",
    sourceUrl: "https://www.rice.edu/events",
    source: "Meetup",
    description:
      "Rice University's annual fall celebration on the beautiful shaded campus with food, music, games, and student organizations.",
    brandFitScore: 8,
    audienceFit: "College students and faculty 18–30, academic/wellness-oriented, higher income, health-aware",
    samplingViability: "High",
    activationIdea:
      "Sampling booth in the student vendor section. 'Study Smart, Drink Clean' angle. Partner with Rice student wellness orgs for co-branding.",
    permitConsiderations: "Vendor approval through Rice University Student Activities. Apply via Rice student organizations office.",
    reasoning:
      "Rice students skew health-conscious, high-income, and brand-aware. Beautiful outdoor campus setting. Smaller than UH but higher brand affinity audience.",
    status: "pending",
    discoveredAt: "2026-04-07T08:00:00",
    calendarAdded: false,
  },
  {
    id: "37",
    name: "Houston Roller Derby Bout",
    date: "2026-10-24T18:00:00",
    endDate: "2026-10-24T22:00:00",
    location: "Bayou Event Center",
    address: "9401 Knight Rd, Houston, TX 77045",
    estimatedAttendance: 1500,
    eventType: "Sports",
    isOutdoor: false,
    isRecurring: true,
    recurringPattern: "Monthly",
    sourceUrl: "https://www.bayoucityrollers.com",
    source: "Eventbrite",
    description:
      "Houston's Bayou City Rollers host monthly roller derby bouts drawing a passionate, alternative crowd of fans and athletes.",
    brandFitScore: 7,
    audienceFit: "Alternative and athletic crowd 21–40, female-skewing, fierce and fun brand loyalists",
    samplingViability: "High",
    activationIdea:
      "'Roll with Be Love' activation. Sponsor the halftime refreshment zone. Branded cups and skater team co-promotion on social media.",
    permitConsiderations: "Coordinate with Bayou City Rollers management for vendor spot. Very accessible and community-friendly organization.",
    reasoning:
      "Niche but deeply loyal community. Female-skewing athletic audience aligns perfectly with Be Love. Low competition for brand partners in this space.",
    status: "pending",
    discoveredAt: "2026-04-07T08:00:00",
    calendarAdded: false,
  },
  {
    id: "38",
    name: "Houston Fit Expo",
    date: "2026-10-31T09:00:00",
    endDate: "2026-11-01T18:00:00",
    location: "NRG Center",
    address: "1 NRG Pkwy, Houston, TX 77054",
    estimatedAttendance: 28000,
    eventType: "Fitness",
    isOutdoor: false,
    isRecurring: true,
    recurringPattern: "Annual",
    sourceUrl: "https://www.nrgpark.com/fit-expo",
    source: "NRG Park Events",
    description:
      "Two-day fitness and bodybuilding expo featuring supplement brands, fitness equipment, athlete appearances, competitions, and wellness product demos.",
    brandFitScore: 9,
    audienceFit: "Fitness enthusiasts and athletes 18–40, supplement-aware, high product trial motivation",
    samplingViability: "High",
    activationIdea:
      "Prime sampling booth in the nutrition/supplement section. 'Clean Performance Fuel' positioning. Athlete ambassador appearances at the booth. Free sample + coupon handout strategy.",
    permitConsiderations: "Exhibitor application through Fit Expo organizers. 2-day commitment. Booth fee $1,500–$3,000. High-volume sampling needed — plan for 2,000+ samples per day.",
    reasoning:
      "Attendees at fitness expos are in full product discovery mode. Very high sampling receptivity. 28K over 2 days with strong repeat visitors.",
    status: "pending",
    discoveredAt: "2026-04-07T08:00:00",
    calendarAdded: false,
  },
];
